
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fasan
 */

import java.util.*;
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    //Crear variables de Nombre, Apellido, Edad, Nota, Scanner, Random, y Metodos
    private static String nombre;
    private static String apellido;
    private  static int edad;
  
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido");

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Edad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(Edad, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        nombre = jTextField1.getText();
        JOptionPane.showMessageDialog(null,"Nombre guardado");
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
        edad = Integer.parseInt(Edad.getText());
        if (edad <18) {
            JOptionPane.showMessageDialog(rootPane, "Edad debe de ser mayor a 18","Swing Tester", JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Edad guardada");
        }
        Edad.setText("");
    }//GEN-LAST:event_EdadActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
        apellido = Apellido.getText();
        JOptionPane.showMessageDialog(null,"Apellido guardado");
        Apellido.setText("");
        
    }//GEN-LAST:event_ApellidoActionPerformed

   
    
    private static int factorial(int limite) {
        if (limite ==0) {
            return 1;
        }
        int factorial = 1;
        for (int i = 1; i <=limite;i++) {
            factorial = factorial*i;
        }
        return factorial;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Crear arrayList de Clases tipo Estudiante
         ArrayList<Estudiantes> estudiantes = new ArrayList();
          Random random = new Random();
         Scanner entrada = new Scanner(System.in);
          Metodos mate = new Metodos();
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        char seguir = 's';
        do {
        
        //Al comienzo del examen, el estudiante tiene 0 correctas
        int correctas = 0;
        
            System.out.println("---Bienvenidos a su examen de Matematicas!---");
            System.out.print("Se incluyen los siguientes temas: ");
            System.out.println("1) Determinantes\n2) Factoriales\n3) Fibonnaci\n4) Sumatorias");
            System.out.println("Respondera 8 preguntas. Se pasa con almenos 60%\n\n");
            //Hacer loop para las 8 preguntas
            for (int i = 1;i<=8;i++) {
                System.out.println("Pregunta "+i+": \n");
                //Crear un digito random del 0 al 3, para ver que problema resolvera el estudiantes;
                int pregunta = random.nextInt(4);
                //Switch para ver que pregunta realizara el estudiante
                switch(pregunta) {
                    //Pregunta de determinantes
                    //Cada vez que responda correctamente el usuario, se le agrega 1 valor a las correctas
                    case 0-> {
                        //Crear determinante con metodos de la clases Metodos
                        int[][] matriz = mate.crearMatriz();
                        //Imprimir Matirz
                        mate.printMatriz(matriz);
                        System.out.println("Cual es la determinante de la siguiente Matriz? ");
                        //Guardar la respuesta de la funcion
                        int respuesta = mate.determinanteMatriz(matriz);
                        int usuarioRespuesta = entrada.nextInt();
                        if (respuesta==usuarioRespuesta){
                            System.out.println("Correcto! ");
                            correctas++;
                        }
                        else {
                            System.out.println("Incorrecto!");
                            System.out.println("La respuesta correcta era: "+respuesta);
                        }
                        break;
                    }
                    //Pregunta de sumatoria
                    case 1-> {
                        //Ver el limite de la sumatoria con numero random
                        int limite = random.nextInt(101);
                        System.out.println("Cual es la sumatoria de los numeros hasta el "+limite+"? ");
                        int respuesta = mate.sumatoria(limite);
                        int respuestaUsuario = entrada.nextInt();
                        if (respuesta==respuestaUsuario) {
                            System.out.println("Correcto!");
                            correctas++;
                        }
                        else {
                            System.out.println("Incorrecto!");
                            System.out.println("La respuesta correcta fue: "+respuesta);
                        }
                        break;
                    }
                    //Pregunta de factorial
                    case 2-> {
                        int limite = random.nextInt(10)+1;
                        System.out.println("Cual es el factorial de "+limite+"? ");
                        int respuesta = factorial(limite);
                        int respuestaUsuario = entrada.nextInt();
                        if (respuesta==respuestaUsuario) {
                            System.out.println("Correcto!");
                            correctas++;
                        }
                        else {
                            System.out.println("Incorrecto!");
                            System.out.println("La respuesta correcta fue: "+respuesta);
                        }
                        break;
                    }
                    //Pregunta de fibonnaci
                    case 3-> {
                        int limite = random.nextInt(13);
                        System.out.println("Cual es el valor del termino "+limite+" en la secuencia fibonnaci? ");
                        int respuesta = mate.fibonacci(limite);
                        int respuestaUsuario = entrada.nextInt();
                        if (respuesta==respuestaUsuario) {
                            System.out.println("Correcto!");
                            correctas++;
                        }
                        else {
                            System.out.println("Incorrecto!");
                            System.out.println("La respuesta correcta fue: "+respuesta);
                        }
                        break;
                    }
                    
                }     
            }
            //Despues de terminar con las 8 preguntas, hay que calcular la nota del estudiante
            double nota = ((double)correctas/8);
            nota = nota*100;
            String estado;
            if (nota <60.0) {
                estado = "REPROBADO";
            }
            else {
                estado = "APROBADO";
            }
            //Crear nuevo objeto de estudiante y despues agregarlo al arrayList
            Estudiantes estudiante = new Estudiantes(nombre,apellido,edad,nota,estado);
            estudiantes.add(estudiante);
            //Ver si otro estudiante desea hacer el examen
            System.out.println("Desea otro estudiante hacer el examen? (s,n)");
            seguir = entrada.next().charAt(0);
            if (Character.toLowerCase(seguir)!='s'&&Character.toLowerCase(seguir)!='n') {
                System.out.println("Ingrese un valor correcto ");
                seguir = entrada.next().charAt(0);
            }
            
            
        } while (Character.toLowerCase(seguir)=='s');
        
        //Imprimir los resultado de todos los estudiantes
        for (int i = 0; i<estudiantes.size();i++) {
            System.out.println(estudiantes.get(i).toString());
        }
        System.exit(0);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Edad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
